### ISSUE TITLE
mysql cannot start (any version)

### ISSUE THREAD

**Issue by simiula** [devilbox/devilbox.org#1]
ERROR: for mysql  Cannot create container for service mysql: invalid bind mount spec "a5e2a2a82da96e8f5fe795d7cb212128ce8c37e47f58dcdc195d48007121733e:etc/mysql/docker-default.d:rw": invalid volume specification: 'a5e2a2a82da96e8f5fe795d7cb212128ce8c37e47f58dcdc195d48007121733e:etc/mysql/docker-default.d:rw': invalid mount config for type "volume": invalid mount path: 'etc/mysql/docker-default.d' mount path must be absolute
I tested on two different Macs (Sierra and High Sierra) same error.
Installed latest version: yesterday.

**Comment by simiula** [comment]
Update: I did a few times
docker-compose rm -f
and now it's running...

**Comment by krukiv-kut** [comment]
Exactly same issue. And exactly same solution works (Windows 10)

**Comment by cytopia** [comment]
For issues regarding the Devilbox, please head over to: https://github.com/cytopia/devilbox
