### ISSUE TITLE
Unable to run docker-compose on elementary os

### ISSUE THREAD

**Issue by Abhinav1217** [devilbox/devilbox.org#4]
I have downloaded the latest docker following steps from https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1 ( replacing  ` $(lsb_release -cs) ` with `xenial` because it was causing error on elementary os ) 

I then installed latest docker-compose following instructions at https://github.com/docker/compose/releases , 

Then I cloned the devilbox repo and copied example file for .env, but I am unable to get it started, This is what I am getting on terminal.

```
abhinav@Abhinav-ele:~/Projcts/Podev/devilbox$ docker -v
Docker version 17.12.0-ce, build c97c6d6
abhinav@Abhinav-ele:~/Projcts/Podev/devilbox$ docker-compose -v
docker-compose version 1.8.0, build unknown
abhinav@Abhinav-ele:~/Projcts/Podev/devilbox$
abhinav@Abhinav-ele:~/Projcts/Podev/devilbox$ docker-compose up
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

What should I do?

**Comment by cytopia** [comment]
Looks like your docker-compose is too old. 1.9 is required. Refer to the documentation: https://github.com/cytopia/devilbox/blob/master/docs/README.md#4-requirements

Also, the place for issues is here: https://github.com/cytopia/devilbox/issues ;-)

To get a recent docker-compose version, follow their guide here: https://docs.docker.com/compose/install/
