### ISSUE TITLE
AutoDNS fails on windows 

### ISSUE THREAD

**Issue by jhaveDK** [devilbox/devilbox.org#7]
As default DNS points to 172.16.238.1 but the windows server dont have access to the network between the docker containers i have change it to 127.0.0.1 in the composer yaml file, but its still dont work

domain.loc. 3600 IN A 172.16.238.1.

**Comment by cytopia** [comment]
Hi @jhaveDK 

Did you read through the documentation for Windows 7 (Docker Toolbox):

https://devilbox.readthedocs.io/en/latest/intermediate/setup-auto-dns.html#docker-toolbox

Also note, that the official Devilbox Github repository is here: https://github.com/cytopia/devilbox

If the documentation does not resolve your issue feel free to open up an issue at the official repository.
I will close this one here.
